### ISSUE TITLE
options: {showAuth: true} throws error

### ISSUE THREAD

**Issue by jack0088** [danielb2/blipp#26]
Is this me or is it a bug? As soon as I add showAuth to the options I get an error: "showAuth" is not allowed

(I use glue) Here's my manifest:

const manifest = { server: {}, connections: [ {host: "localhost", port: 8000} ], registrations: [ {plugin: "hapi-auth-basic"}, {plugin: "blipp", options: {showAuth: true}} ] }

Now the interesting part. If I remove showAuth from options and then go to the module /node_modules/blipp/lib/index.js and edit line 11 to be showAuth: Joi.boolean().default(true) // instead of false
then it works!

How can this be?

**Comment by abramjstamper** [comment]
I also had this same issue at first. Then, I tried a different syntax. It worked the second way. I didn't modify anything in the module to the get this to work. I know this is from 2016, but I figure it might help others who are also wondering how to specify options since the READEME doesn't cover it. Hopefully this will prevent future headaches.

Doesn't Work:
```await server.register(require('blipp'), { showAuth: true });```

Works:
```await server.register({plugin: require('blipp'), options: { showAuth: true }});```

**Comment by danielb2** [comment]
I've updated the read me with a comment which shows the working line. Closing this. Let me know if I should re-open.
